#!/usr/bin/env bash
# The script displays the content of the file /etc/passwd

while read passwd_line; do
    # Extract username, user ID (UID), and home directory path using cut
    username=$(echo "$passwd_line" | cut -d ':' -f1)
    uid=$(echo "$passwd_line" | cut -d ':' -f3)
    home=$(echo "$passwd_line" | cut -d ':' -f6)
    
    # Print user information
    echo "User: $username, ID: $uid, Home: $home"
done < "/etc/passwd"
