#!/usr/bin/env bash
# AUTHOR: Edwardmurithi <murithiedward330@gmail.com>
# This script that displays Best School 10 times.

counter=1
while [ $counter -le 10 ]; do
	echo "Best School"
	(( counter+=1 ))
done
