#!/usr/bin/env bash
# AUTHOR: Edwardmurithi <murithiedward330@gmail.com>
# This script that displays Best School 10 times.

counter=1

until [ $counter -gt 10 ]; do
	echo "Best School"
	(( counter++ ))
done
