#!/usr/bin/env bash
# AUTHOR: Edwardmurithi <murithiedward330@gamil.com>
# This script displays numbers from 1 to 20 and:
# Displays 4 and then bad luck from China for the 4th loop iteration
# Displays 9 and then bad luck from Japan for the 9th loop iteration
# Displays 17 and then bad luck from Italy for the 17th loop iteration

counter=0

while [ $counter -le 20 ]; do
	# Use a case statement to check the value of the counter
	echo "$counter"
	case $counter in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;

	esac

	# Increment the counter
	((counter++))

done

