#!/usr/bin/env bash
# This script displays:
#	The content of the current directory
#	In a list format
#	Where only the part of the name after the first dash is displayed 

for file in $(ls -I '.*'); do
	filename=$(echo "$file" | cut -d '-' -f 2-)
	echo "$filename"
done
