#!/usr/bin/env bash

hour=0
minute=1

while [ $hour -le 12 ] && [ $minute -le 59 ]; do
	printf "%02d:%02d\n" $hour $minute

	(( minute++ ))
	if [ $minute -eq 60 ]; then
		minute=1
		(( hour++ ))
		if [ $hour -eq 13 ]; then
			hour=1
		fi
	fi
done | head -n 70
